name       : qt6-scxml
version    : 6.2.1
release    : 1
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.1/submodules/qtscxml-everywhere-src-6.2.1.tar.xz : cff613f68af98f4bdc1e40df0b6515b69175e10e83c551a57ee5db4359505767
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 SCXML components
description: |
    The Qt SCXML module provides functionality to create state machines from SCXML files. This includes both dynamically creating state machines (loading the SCXML file and instantiating states and transitions) and generating a C++ file that has a class implementing the state machine.
builddeps  :
    - pkgconfig(Qt6Qml)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
